package io.jejuwn.mapper;

import io.jejuwn.model.Address;
import io.jejuwn.model.AddressExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.annotation.Primary;

@Mapper
@Primary
public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    long countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int deleteByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int insert(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int insertSelective(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    Address selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int updateByExampleSelective(@Param("row") Address row, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int updateByExample(@Param("row") Address row, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int updateByPrimaryKeySelective(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADDRESS
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    int updateByPrimaryKey(Address row);
}