package io.jejuwn.mapper;

import io.jejuwn.model.BlogUserTest;
import io.jejuwn.model.BlogUserTestExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogUserTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    long countByExample(BlogUserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int deleteByExample(BlogUserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int insert(BlogUserTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int insertSelective(BlogUserTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    List<BlogUserTest> selectByExample(BlogUserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    BlogUserTest selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int updateByExampleSelective(@Param("row") BlogUserTest row, @Param("example") BlogUserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int updateByExample(@Param("row") BlogUserTest row, @Param("example") BlogUserTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int updateByPrimaryKeySelective(BlogUserTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_USER_TEST
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    int updateByPrimaryKey(BlogUserTest row);
}