package io.jejuwn.mapper;

import io.jejuwn.model.CartItem;
import io.jejuwn.model.CartItemExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    CartItem selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") CartItem row, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") CartItem row, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART_ITEM
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(CartItem row);
}