package io.jejuwn.mapper;

import io.jejuwn.model.Cart;
import io.jejuwn.model.CartExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    Cart selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(Cart row);
}