package io.jejuwn.mapper;

import io.jejuwn.model.ProductTraffic;
import io.jejuwn.model.ProductTrafficExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductTrafficMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(ProductTrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(ProductTrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(ProductTraffic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(ProductTraffic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<ProductTraffic> selectByExample(ProductTrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    ProductTraffic selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") ProductTraffic row, @Param("example") ProductTrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") ProductTraffic row, @Param("example") ProductTrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(ProductTraffic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TRAFFIC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(ProductTraffic row);
}