package io.jejuwn.mapper;

import io.jejuwn.model.ProductComment;
import io.jejuwn.model.ProductCommentExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(ProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(ProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(ProductComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(ProductComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<ProductComment> selectByExample(ProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    ProductComment selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") ProductComment row, @Param("example") ProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") ProductComment row, @Param("example") ProductCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(ProductComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMMENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(ProductComment row);
}