package io.jejuwn.mapper;

import io.jejuwn.model.ProductInfo;
import io.jejuwn.model.ProductInfoExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(ProductInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(ProductInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    ProductInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") ProductInfo row, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") ProductInfo row, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(ProductInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(ProductInfo row);
}