package io.jejuwn.mapper;

import io.jejuwn.model.Promotion;
import io.jejuwn.model.PromotionExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    long countByExample(PromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int deleteByExample(PromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int insert(Promotion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int insertSelective(Promotion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    List<Promotion> selectByExample(PromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    Promotion selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int updateByExampleSelective(@Param("row") Promotion row, @Param("example") PromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int updateByExample(@Param("row") Promotion row, @Param("example") PromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int updateByPrimaryKeySelective(Promotion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMOTION
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    int updateByPrimaryKey(Promotion row);
}