package io.jejuwn.mapper;

import io.jejuwn.model.Reservation;
import io.jejuwn.model.ReservationExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(Reservation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(Reservation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<Reservation> selectByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    Reservation selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") Reservation row, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") Reservation row, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(Reservation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(Reservation row);
}