package io.jejuwn.mapper;

import io.jejuwn.model.Usertbl;
import io.jejuwn.model.UsertblExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsertblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(UsertblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(UsertblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(Usertbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(Usertbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<Usertbl> selectByExample(UsertblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    Usertbl selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") Usertbl row, @Param("example") UsertblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") Usertbl row, @Param("example") UsertblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(Usertbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERTBL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(Usertbl row);
}