package io.jejuwn.mapper;

import io.jejuwn.model.UserOrder;
import io.jejuwn.model.UserOrderExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    long countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insert(UserOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int insertSelective(UserOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    List<UserOrder> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    UserOrder selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExampleSelective(@Param("row") UserOrder row, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByExample(@Param("row") UserOrder row, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKeySelective(UserOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ORDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    int updateByPrimaryKey(UserOrder row);
}