package io.jejuwn.model;

import java.math.BigDecimal;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.USER_ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.ADDRESS_LINE1
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private String addressLine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.ADDRESS_LINE2
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private String addressLine2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.CITY
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.PHONE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.ID
     *
     * @return the value of ADDRESS.ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.ID
     *
     * @param id the value for ADDRESS.ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.USER_ID
     *
     * @return the value of ADDRESS.USER_ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.USER_ID
     *
     * @param userId the value for ADDRESS.USER_ID
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.ADDRESS_LINE1
     *
     * @return the value of ADDRESS.ADDRESS_LINE1
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.ADDRESS_LINE1
     *
     * @param addressLine1 the value for ADDRESS.ADDRESS_LINE1
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.ADDRESS_LINE2
     *
     * @return the value of ADDRESS.ADDRESS_LINE2
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.ADDRESS_LINE2
     *
     * @param addressLine2 the value for ADDRESS.ADDRESS_LINE2
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.CITY
     *
     * @return the value of ADDRESS.CITY
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.CITY
     *
     * @param city the value for ADDRESS.CITY
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.POSTAL_CODE
     *
     * @return the value of ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.POSTAL_CODE
     *
     * @param postalCode the value for ADDRESS.POSTAL_CODE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.PHONE
     *
     * @return the value of ADDRESS.PHONE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.PHONE
     *
     * @param phone the value for ADDRESS.PHONE
     *
     * @mbg.generated Wed Jun 29 21:16:35 KST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

	@Override
	public String toString() {
		return "Address [id=" + id + ", userId=" + userId + ", addressLine1=" + addressLine1 + ", addressLine2="
				+ addressLine2 + ", city=" + city + ", postalCode=" + postalCode + ", phone=" + phone + "]";
	}
    
}