package io.jejuwn.model;

import java.math.BigDecimal;
import java.util.Date;

import lombok.ToString;

@ToString
public class BlogUserTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.USER_ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.TITLE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.CONTENT
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.REGDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_USER_TEST.UPDATEDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.ID
     *
     * @return the value of BLOG_USER_TEST.ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.ID
     *
     * @param id the value for BLOG_USER_TEST.ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.USER_ID
     *
     * @return the value of BLOG_USER_TEST.USER_ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.USER_ID
     *
     * @param userId the value for BLOG_USER_TEST.USER_ID
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.TITLE
     *
     * @return the value of BLOG_USER_TEST.TITLE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.TITLE
     *
     * @param title the value for BLOG_USER_TEST.TITLE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.CONTENT
     *
     * @return the value of BLOG_USER_TEST.CONTENT
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.CONTENT
     *
     * @param content the value for BLOG_USER_TEST.CONTENT
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.REGDATE
     *
     * @return the value of BLOG_USER_TEST.REGDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.REGDATE
     *
     * @param regdate the value for BLOG_USER_TEST.REGDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_USER_TEST.UPDATEDATE
     *
     * @return the value of BLOG_USER_TEST.UPDATEDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_USER_TEST.UPDATEDATE
     *
     * @param updatedate the value for BLOG_USER_TEST.UPDATEDATE
     *
     * @mbg.generated Fri Jul 01 18:20:49 KST 2022
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}