package io.jejuwn.model;

import java.math.BigDecimal;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.ID
     *
     * @return the value of CART.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.ID
     *
     * @param id the value for CART.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.TOKEN
     *
     * @return the value of CART.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.TOKEN
     *
     * @param token the value for CART.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setToken(BigDecimal token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.USER_ID
     *
     * @return the value of CART.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.USER_ID
     *
     * @param userId the value for CART.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

	@Override
	public String toString() {
		return "Cart [id=" + id + ", token=" + token + ", userId=" + userId + "]";
	}
    
}