package io.jejuwn.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="product_seq")
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CATEGORY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column(name = "user_id")
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.REGION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.ID
     *
     * @return the value of PRODUCT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.ID
     *
     * @param id the value for PRODUCT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.NAME
     *
     * @return the value of PRODUCT.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.NAME
     *
     * @param name the value for PRODUCT.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CATEGORY
     *
     * @return the value of PRODUCT.CATEGORY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CATEGORY
     *
     * @param category the value for PRODUCT.CATEGORY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setCategory(BigDecimal category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.USER_ID
     *
     * @return the value of PRODUCT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.USER_ID
     *
     * @param userId the value for PRODUCT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.REGION
     *
     * @return the value of PRODUCT.REGION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.REGION
     *
     * @param region the value for PRODUCT.REGION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRegion(BigDecimal region) {
        this.region = region;
    }

	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", category=" + category + ", userId=" + userId + ", region="
				+ region + "]";
	}
    
}