package io.jejuwn.model;

import java.math.BigDecimal;

public class ProductTraffic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TRAFFIC.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TRAFFIC.LATITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TRAFFIC.LONGITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TRAFFIC.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TRAFFIC.KEYWORD
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TRAFFIC.ID
     *
     * @return the value of PRODUCT_TRAFFIC.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TRAFFIC.ID
     *
     * @param id the value for PRODUCT_TRAFFIC.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TRAFFIC.LATITUDE
     *
     * @return the value of PRODUCT_TRAFFIC.LATITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TRAFFIC.LATITUDE
     *
     * @param latitude the value for PRODUCT_TRAFFIC.LATITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TRAFFIC.LONGITUDE
     *
     * @return the value of PRODUCT_TRAFFIC.LONGITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TRAFFIC.LONGITUDE
     *
     * @param longitude the value for PRODUCT_TRAFFIC.LONGITUDE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TRAFFIC.PRODUCT_ID
     *
     * @return the value of PRODUCT_TRAFFIC.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TRAFFIC.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_TRAFFIC.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TRAFFIC.KEYWORD
     *
     * @return the value of PRODUCT_TRAFFIC.KEYWORD
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TRAFFIC.KEYWORD
     *
     * @param keyword the value for PRODUCT_TRAFFIC.KEYWORD
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

	@Override
	public String toString() {
		return "ProductTraffic [id=" + id + ", latitude=" + latitude + ", longitude=" + longitude + ", productId="
				+ productId + ", keyword=" + keyword + "]";
	}
    
}