package io.jejuwn.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.CONTENT_EXTRA
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String contentExtra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.START_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.END_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PRICE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.HIT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal hit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.MAX_CAPACITY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal maxCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.ADDRESS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.ID
     *
     * @return the value of PRODUCT_INFO.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.ID
     *
     * @param id the value for PRODUCT_INFO.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PRODUCT_ID
     *
     * @return the value of PRODUCT_INFO.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_INFO.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.CONTENT
     *
     * @return the value of PRODUCT_INFO.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.CONTENT
     *
     * @param content the value for PRODUCT_INFO.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.CONTENT_EXTRA
     *
     * @return the value of PRODUCT_INFO.CONTENT_EXTRA
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getContentExtra() {
        return contentExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.CONTENT_EXTRA
     *
     * @param contentExtra the value for PRODUCT_INFO.CONTENT_EXTRA
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setContentExtra(String contentExtra) {
        this.contentExtra = contentExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.REGDATE
     *
     * @return the value of PRODUCT_INFO.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.REGDATE
     *
     * @param regdate the value for PRODUCT_INFO.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.UPDATEDATE
     *
     * @return the value of PRODUCT_INFO.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.UPDATEDATE
     *
     * @param updatedate the value for PRODUCT_INFO.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.START_TIME
     *
     * @return the value of PRODUCT_INFO.START_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.START_TIME
     *
     * @param startTime the value for PRODUCT_INFO.START_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.END_TIME
     *
     * @return the value of PRODUCT_INFO.END_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.END_TIME
     *
     * @param endTime the value for PRODUCT_INFO.END_TIME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PRICE
     *
     * @return the value of PRODUCT_INFO.PRICE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PRICE
     *
     * @param price the value for PRODUCT_INFO.PRICE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.HIT
     *
     * @return the value of PRODUCT_INFO.HIT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getHit() {
        return hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.HIT
     *
     * @param hit the value for PRODUCT_INFO.HIT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setHit(BigDecimal hit) {
        this.hit = hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.MAX_CAPACITY
     *
     * @return the value of PRODUCT_INFO.MAX_CAPACITY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.MAX_CAPACITY
     *
     * @param maxCapacity the value for PRODUCT_INFO.MAX_CAPACITY
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setMaxCapacity(BigDecimal maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.ADDRESS
     *
     * @return the value of PRODUCT_INFO.ADDRESS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.ADDRESS
     *
     * @param address the value for PRODUCT_INFO.ADDRESS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

	@Override
	public String toString() {
		return "ProductInfo [id=" + id + ", productId=" + productId + ", content=" + content + ", contentExtra="
				+ contentExtra + ", regdate=" + regdate + ", updatedate=" + updatedate + ", startTime=" + startTime
				+ ", endTime=" + endTime + ", price=" + price + ", hit=" + hit + ", maxCapacity=" + maxCapacity
				+ ", address=" + address + "]";
	}
    
}