package io.jejuwn.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_COMMENT.RATING
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.ID
     *
     * @return the value of PRODUCT_COMMENT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.ID
     *
     * @param id the value for PRODUCT_COMMENT.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.CONTENT
     *
     * @return the value of PRODUCT_COMMENT.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.CONTENT
     *
     * @param content the value for PRODUCT_COMMENT.CONTENT
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.USER_ID
     *
     * @return the value of PRODUCT_COMMENT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.USER_ID
     *
     * @param userId the value for PRODUCT_COMMENT.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.PRODUCT_ID
     *
     * @return the value of PRODUCT_COMMENT.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_COMMENT.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.REGDATE
     *
     * @return the value of PRODUCT_COMMENT.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.REGDATE
     *
     * @param regdate the value for PRODUCT_COMMENT.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.UPDATEDATE
     *
     * @return the value of PRODUCT_COMMENT.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.UPDATEDATE
     *
     * @param updatedate the value for PRODUCT_COMMENT.UPDATEDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_COMMENT.RATING
     *
     * @return the value of PRODUCT_COMMENT.RATING
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_COMMENT.RATING
     *
     * @param rating the value for PRODUCT_COMMENT.RATING
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRating(BigDecimal rating) {
        this.rating = rating;
    }

	@Override
	public String toString() {
		return "ProductComment [id=" + id + ", content=" + content + ", userId=" + userId + ", productId=" + productId
				+ ", regdate=" + regdate + ", updatedate=" + updatedate + ", rating=" + rating + "]";
	}
    
}