package io.jejuwn.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class ProductLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_LIKE.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="product_lik_seq")
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_LIKE.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_LIKE.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_LIKE.ID
     *
     * @return the value of PRODUCT_LIKE.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_LIKE.ID
     *
     * @param id the value for PRODUCT_LIKE.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_LIKE.USER_ID
     *
     * @return the value of PRODUCT_LIKE.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_LIKE.USER_ID
     *
     * @param userId the value for PRODUCT_LIKE.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_LIKE.PRODUCT_ID
     *
     * @return the value of PRODUCT_LIKE.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_LIKE.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_LIKE.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

	@Override
	public String toString() {
		return "ProductLike [id=" + id + ", userId=" + userId + ", productId=" + productId + "]";
	}
    
}