package io.jejuwn.model;

import java.math.BigDecimal;

public class Promotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.CODE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.PROMOTION_VALUE_DEC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal promotionValueDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.PROMOTION_VALUE_ABS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal promotionValueAbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.ID
     *
     * @return the value of PROMOTION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.ID
     *
     * @param id the value for PROMOTION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.CODE
     *
     * @return the value of PROMOTION.CODE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.CODE
     *
     * @param code the value for PROMOTION.CODE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.PROMOTION_VALUE_DEC
     *
     * @return the value of PROMOTION.PROMOTION_VALUE_DEC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getPromotionValueDec() {
        return promotionValueDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.PROMOTION_VALUE_DEC
     *
     * @param promotionValueDec the value for PROMOTION.PROMOTION_VALUE_DEC
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setPromotionValueDec(BigDecimal promotionValueDec) {
        this.promotionValueDec = promotionValueDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.PROMOTION_VALUE_ABS
     *
     * @return the value of PROMOTION.PROMOTION_VALUE_ABS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getPromotionValueAbs() {
        return promotionValueAbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.PROMOTION_VALUE_ABS
     *
     * @param promotionValueAbs the value for PROMOTION.PROMOTION_VALUE_ABS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setPromotionValueAbs(BigDecimal promotionValueAbs) {
        this.promotionValueAbs = promotionValueAbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.PRODUCT_ID
     *
     * @return the value of PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.PRODUCT_ID
     *
     * @param productId the value for PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }
}