package io.jejuwn.model;

import java.math.BigDecimal;

public class Promotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.CODE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.PROMOTION_VALUE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    private BigDecimal promotionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    private BigDecimal productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.ID
     *
     * @return the value of PROMOTION.ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.ID
     *
     * @param id the value for PROMOTION.ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.CODE
     *
     * @return the value of PROMOTION.CODE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.CODE
     *
     * @param code the value for PROMOTION.CODE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.PROMOTION_VALUE
     *
     * @return the value of PROMOTION.PROMOTION_VALUE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public BigDecimal getPromotionValue() {
        return promotionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.PROMOTION_VALUE
     *
     * @param promotionValue the value for PROMOTION.PROMOTION_VALUE
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public void setPromotionValue(BigDecimal promotionValue) {
        this.promotionValue = promotionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMOTION.PRODUCT_ID
     *
     * @return the value of PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMOTION.PRODUCT_ID
     *
     * @param productId the value for PROMOTION.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 05 16:30:18 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

	@Override
	public String toString() {
		return "Promotion [id=" + id + ", code=" + code + ", promotionValueDec=" + promotionValueDec
				+ ", promotionValueAbs=" + promotionValueAbs + ", productId=" + productId + "]";
	}
    
}