package io.jejuwn.model;

import java.math.BigDecimal;
import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal reservation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.RESERVATION_DATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private Date reservationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.ID
     *
     * @return the value of RESERVATION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.ID
     *
     * @param id the value for RESERVATION.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.NAME
     *
     * @return the value of RESERVATION.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.NAME
     *
     * @param name the value for RESERVATION.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.REGDATE
     *
     * @return the value of RESERVATION.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.REGDATE
     *
     * @param regdate the value for RESERVATION.REGDATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.USER_ID
     *
     * @return the value of RESERVATION.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.USER_ID
     *
     * @param userId the value for RESERVATION.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.RESERVATION
     *
     * @return the value of RESERVATION.RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getReservation() {
        return reservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.RESERVATION
     *
     * @param reservation the value for RESERVATION.RESERVATION
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setReservation(BigDecimal reservation) {
        this.reservation = reservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.RESERVATION_DATE
     *
     * @return the value of RESERVATION.RESERVATION_DATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public Date getReservationDate() {
        return reservationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.RESERVATION_DATE
     *
     * @param reservationDate the value for RESERVATION.RESERVATION_DATE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.STATUS
     *
     * @return the value of RESERVATION.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.STATUS
     *
     * @param status the value for RESERVATION.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION.PRODUCT_ID
     *
     * @return the value of RESERVATION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION.PRODUCT_ID
     *
     * @param productId the value for RESERVATION.PRODUCT_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

	@Override
	public String toString() {
		return "Reservation [id=" + id + ", name=" + name + ", regdate=" + regdate + ", userId=" + userId
				+ ", reservation=" + reservation + ", reservationDate=" + reservationDate + ", status=" + status
				+ ", productId=" + productId + "]";
	}
    
}