package io.jejuwn.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Builder
@ToString
@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
@Table(name="Usertbl")
public class Usertbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "USERTBL_SEQ")
	@SequenceGenerator(sequenceName = "customer_seq", allocationSize = 1, name = "USERTBL_SEQ")
	@Id
	@Column(name = "id")
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.NICK
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    @Column(name = "nick")
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.PASS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column(name = "pass")
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.GENDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.AGE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.EMAIL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTBL.ROLE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
	@Column
    private BigDecimal role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.ID
     *
     * @return the value of USERTBL.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.ID
     *
     * @param id the value for USERTBL.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.NAME
     *
     * @return the value of USERTBL.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.NAME
     *
     * @param name the value for USERTBL.NAME
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.NICK
     *
     * @return the value of USERTBL.NICK
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.NICK
     *
     * @param nick the value for USERTBL.NICK
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.PASS
     *
     * @return the value of USERTBL.PASS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.PASS
     *
     * @param pass the value for USERTBL.PASS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.GENDER
     *
     * @return the value of USERTBL.GENDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.GENDER
     *
     * @param gender the value for USERTBL.GENDER
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setGender(BigDecimal gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.AGE
     *
     * @return the value of USERTBL.AGE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.AGE
     *
     * @param age the value for USERTBL.AGE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setAge(BigDecimal age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.EMAIL
     *
     * @return the value of USERTBL.EMAIL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.EMAIL
     *
     * @param email the value for USERTBL.EMAIL
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTBL.ROLE
     *
     * @return the value of USERTBL.ROLE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTBL.ROLE
     *
     * @param role the value for USERTBL.ROLE
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setRole(BigDecimal role) {
        this.role = role;
    }


    
}