package io.jejuwn.model;

import java.math.BigDecimal;

public class UserOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.CART_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.ADDRESS_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ORDER.PROMOTION_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    private BigDecimal promotionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.ID
     *
     * @return the value of USER_ORDER.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.ID
     *
     * @param id the value for USER_ORDER.ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.TOKEN
     *
     * @return the value of USER_ORDER.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.TOKEN
     *
     * @param token the value for USER_ORDER.TOKEN
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setToken(BigDecimal token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.USER_ID
     *
     * @return the value of USER_ORDER.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.USER_ID
     *
     * @param userId the value for USER_ORDER.USER_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.CART_ID
     *
     * @return the value of USER_ORDER.CART_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.CART_ID
     *
     * @param cartId the value for USER_ORDER.CART_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setCartId(BigDecimal cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.ADDRESS_ID
     *
     * @return the value of USER_ORDER.ADDRESS_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.ADDRESS_ID
     *
     * @param addressId the value for USER_ORDER.ADDRESS_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setAddressId(BigDecimal addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.STATUS
     *
     * @return the value of USER_ORDER.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.STATUS
     *
     * @param status the value for USER_ORDER.STATUS
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ORDER.PROMOTION_ID
     *
     * @return the value of USER_ORDER.PROMOTION_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public BigDecimal getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ORDER.PROMOTION_ID
     *
     * @param promotionId the value for USER_ORDER.PROMOTION_ID
     *
     * @mbg.generated Wed Jun 29 20:14:37 KST 2022
     */
    public void setPromotionId(BigDecimal promotionId) {
        this.promotionId = promotionId;
    }
}